export const promise = {
  PENDING: '_PENDING',
  REJECTED: '_REJECTED',
  FULFILLED: '_FULFILLED',
};

export const userTypes = {
  CHANGE_FIRST_NAME: 'CHANGE_FIRST_NAME',
  CHANGE_LAST_NAME: 'CHANGE_LAST_NAME',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_COMPANY_NAME: 'CHANGE_COMPANY_NAME',
};

export const campaingTypes = {
  SEARCH_CAMPAIGN: 'SEARCH_CAMPAIGN_VALUE',
  SELECT_CURRENT_CAMPAIGN: 'SELECT_CURRENT_CAMPAIGN_VALUE',
  CHANGE_CAMPAIGN_OVERVIEW: 'CHANGE_CAMPAIGN_OVERVIEW',
};


export const adTypes = {
  SELECT_AD_TYPE: 'SELECT_AD_TYPE_VALUE',
  CHANGE_AD_UNIT_NAME: 'CHANGE_AD_UNIT_NAME',
  SELECT_AD_UNIT_KEYWORDS: 'SELECT_AD_KEYWORDS_VALUES',
  SWITCH_AD_UNIT: 'SWITCH_AD_UNIT',
  SELECT_AD_UNIT_GROUP_TYPE: 'SELECT_AD_UNIT_GROUP_TYPE_VALUE',
};


export const rulesTypes = {

};


export const adminTypes = {
};